[package]
name = "grpc-server"
version = "0.1.0"
edition = "2021"

[dependencies]
tonic = "0.10"
tonic-reflection = "0.10"
prost = "0.12"
tokio = { version = "1.0", features = ["full"] }
futures = "0.3"

[build-dependencies]
tonic-build = "0.10"
